name: gnu-arm12
on: [push]

jobs:
  build-gnu-arm12:
    runs-on: self-hosted
    container:
      image: xlemonx/arm-gnu-toolchain:12.3.1
      volumes:
        - builds:/builds
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Init environment
        run: git config --global --add safe.directory "*"

      - name: Pull test repo
        run: |
          rm -rf tests_stmepic
          git clone https://github.com/X-Lemon-X/tests_stmepic.git

      - name: Build test repo
        run: |
          cd tests_stmepic
          cmake -B build -G "Ninja" -DCOPY_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
